### ISSUE TITLE
Add support to `traverse_errors`

### ISSUE THREAD

**Issue by vtm9** [mathieuprog/polymorphic_embed#38]
Hey, thx for the so nice library.
Now a standard way to handling errors in ecto changeset `Ecto.changeset.traverse_errors/2` doesn't work as expected with PolymorphicEmbed .

In ecto it works only  for maps with keys `%{cardinality: :one}` or `%{cardinality: :many}` and tag in `@relations [:embed, :assoc]`

https://github.com/elixir-ecto/ecto/blob/1c415141332f4c7df7fd1a8fbbc3b715668ae15b/lib/ecto/changeset.ex#L2937-L2966

Is there any way to include `{:parameterized, PolymorphicEmbed, %{}}` to handling by traverse_erorrs, or create a new function that will be doing the same for `PolymorphicEmbed`?
Thx

**Comment by mathieuprog** [comment]
`PolymorphicEmbed.traverse_errors/2` has been added in version 1.5.0
https://github.com/mathieuprog/polymorphic_embed#traverse_errors2

Let me know if it works for you as expected:)

**Comment by rupurt** [comment]
Works great for me @mathieuprog :beers:

**Comment by mathieuprog** [comment]
Cool 😁 thank you for the feedback!

**Comment by x-ji** [comment]
Just wondering, is there an easy way to tell whether a changeset contains polymorphic embeds or not so that the logic can decide whether to apply `PolymorphicEmbed.traverse_errors/2` or the normal`Ecto.Changeset.traverse_errors/2`? (e.g. in an ErrorView). Or is this function safe to apply to non-polymorphic-embed cases as well?

**Comment by mathieuprog** [comment]
Safe to use for any case
